// text generated by Copilot
const accordions = [
  {
    title: "What is Frontend Mentor, and how will it help me?",
    text: "Frontend Mentor offers realistic coding challenges to help developers improve their frontend coding skils with projects on HTML, CSS and JavaScript. It's suitable for all levels and ideal for portfolio building.",
  },
  {
    title: "Is Frontend Mentor free?",
    text: "Frontend Mentor has both free and premium challenges. The free challenges are available to all users. They're a great way to improve your skills and prepare you for the premium challenges.",
  },
  {
    title: "Can I use Frontend Mentor projects in my portfolio?",
    text: "Yes! You can use any solution you create for a challenge in your portfolio. You can also build projects independently using the designs in the 'Projects' section of the site.",
  },
  {
    title: "How can i get help if I'm stuck on a challenge?",
    text: "The Frontend Mentor community is very active and helpful! Head to the community chat and ask your question there. You'll get help in no time!",
  },
];

export default accordions;
